"""
LangGraph state definition for MethyAgent.

The MethyAgentState TypedDict is the single shared state object
passed between all nodes in the LangGraph StateGraph.
"""
from typing import Annotated, Any, Dict, List, Optional

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class MethyAgentState(TypedDict):
    """
    Shared state for the MethyAgent LangGraph workflow.

    Fields are populated progressively as the graph executes:
      parse_query → run_database_agent → run_literature_agent → generate_report
    """

    # ------------------------------------------------------------------ #
    #  Input                                                               #
    # ------------------------------------------------------------------ #
    raw_query: str
    """The original user query string."""

    parsed_intent: Dict[str, Any]
    """
    Structured intent extracted from raw_query. Keys:
      mode, accessions, cancer_type, platform, data_type,
      year_start, year_end, geo_search_query, pubmed_search_query
    """

    # ------------------------------------------------------------------ #
    #  Agent 1 (DatabaseAgent) outputs                                     #
    # ------------------------------------------------------------------ #
    db_candidates: List[Dict[str, Any]]
    """Datasets found by database search (before download)."""

    db_downloaded: List[str]
    """Accession IDs successfully downloaded by Agent 1."""

    db_failed: List[str]
    """Accession IDs that failed to download in Agent 1."""

    db_skipped: List[str]
    """Accession IDs skipped (already in registry)."""

    # ------------------------------------------------------------------ #
    #  Agent 2 (LiteratureAgent) outputs                                   #
    # ------------------------------------------------------------------ #
    papers_found: List[Dict[str, Any]]
    """Papers retrieved from PubMed/PMC/bioRxiv."""

    lit_candidates: List[Dict[str, Any]]
    """Datasets extracted from literature (before dedup check)."""

    lit_downloaded: List[str]
    """Accession IDs newly downloaded by Agent 2 (not in Agent 1 results)."""

    lit_failed: List[str]
    """Accession IDs that failed to download in Agent 2."""

    lit_skipped: List[str]
    """Accession IDs skipped by Agent 2 (already covered by Agent 1)."""

    # ------------------------------------------------------------------ #
    #  Inter-agent communication                                           #
    # ------------------------------------------------------------------ #
    messages: Annotated[List[BaseMessage], add_messages]
    """
    Message history for Agent reasoning steps.
    Uses LangGraph's add_messages reducer to append (not overwrite).
    """

    # ------------------------------------------------------------------ #
    #  Global                                                              #
    # ------------------------------------------------------------------ #
    error_log: List[str]
    """Accumulated error messages from any node."""

    final_report: Dict[str, Any]
    """Summary report generated by the Reporter node."""

    # ------------------------------------------------------------------ #
    #  Config (passed through, not modified)                               #
    # ------------------------------------------------------------------ #
    config: Dict[str, Any]
    """Full settings dict loaded from settings.yaml."""
